package org.db;

import io.github.cdimascio.dotenv.Dotenv;
import org.db.connection.DbConnection;

import java.sql.SQLOutput;
import java.util.HashMap;
import java.util.Map;

public class Main {
    public static final Dotenv dotenv = Dotenv.load();
    private static final String URL = dotenv.get("URL_JDBC");
    private static final String USER = dotenv.get("USER_JDBC");
    private static final String PASSWORD = dotenv.get("PASSWORD_JDBC");
    public static Map<String, String> dicUsers = new HashMap<>();


    public static void main(String[] args) {
        DbConnection client = new DbConnection(URL,USER,PASSWORD);
        String table = "usuarios";
        try {
            Boolean clientConnect = client.connect();

            dicUsers.put("Joao", "jao@gmail.com");
            dicUsers.put("Maria", "maria@gmail.com");
            dicUsers.put("Pedro", "pedro@gmail.com");
            dicUsers.put("Ana", "ana@gmail.com");
            dicUsers.put("Lucas", "lucas@gmail.com");
            dicUsers.put("Mariana", "mariana@gmail.com");
            dicUsers.put("Gustavo", "gustavo@gmail.com");
            dicUsers.put("Julia", "julia@gmail.com");
            dicUsers.put("Rafael", "rafael@gmail.com");
            dicUsers.put("Beatriz", "beatriz@gmail.com");
            dicUsers.put("Enzo", "enzo@gmail.com");
            dicUsers.put("Laura", "laura@gmail.com");
            dicUsers.put("Guilherme", "guilherme@gmail.com");
            dicUsers.put("Isabela", "isabela@gmail.com");
            dicUsers.put("Matheus", "matheus@gmail.com");
            dicUsers.put("Sofia", "sofia@gmail.com");
            dicUsers.put("Bruno", "bruno@gmail.com");
            dicUsers.put("Camila", "camila@gmail.com");
            dicUsers.put("Felipe", "felipe@gmail.com");
            dicUsers.put("Leticia", "leticia@gmail.com");
            dicUsers.put("Vinicius", "vinicius@gmail.com");
            dicUsers.put("Gabriela", "gabriela@gmail.com");
            dicUsers.put("Leonardo", "leonardo@gmail.com");
            dicUsers.put("Amanda", "amanda@gmail.com");
            dicUsers.put("Thiago", "thiago@gmail.com");
            dicUsers.put("Yasmin", "yasmin@gmail.com");
            dicUsers.put("Daniel", "daniel@gmail.com");
            dicUsers.put("Larissa", "larissa@gmail.com");
            dicUsers.put("Eduardo", "eduardo@gmail.com");
            dicUsers.put("Natalia", "natalia@gmail.com");
            dicUsers.put("Alexandre", "alexandre@gmail.com");
            dicUsers.put("Rafaela", "rafaela@gmail.com");
            dicUsers.put("Rodrigo", "rodrigo@gmail.com");
            dicUsers.put("Manuela", "manuela@gmail.com");
            dicUsers.put("Igor", "igor@gmail.com");
            dicUsers.put("Lorena", "lorena@gmail.com");
            dicUsers.put("Marcelo", "marcelo@gmail.com");
            dicUsers.put("Vitoria", "vitoria@gmail.com");
            dicUsers.put("Ricardo", "ricardo@gmail.com");
            dicUsers.put("Helena", "helena@gmail.com");
            dicUsers.put("Caio", "caio@gmail.com");
            dicUsers.put("Luana", "luana@gmail.com");
            dicUsers.put("Diego", "diego@gmail.com");
            dicUsers.put("Carolina", "carolina@gmail.com");
            dicUsers.put("Henrique", "henrique@gmail.com");
            dicUsers.put("Alice", "alice@gmail.com");
            dicUsers.put("Fernando", "fernando@gmail.com");
            dicUsers.put("Clara", "clara@gmail.com");
            dicUsers.put("Carlos", "carlos@gmail.com");
            dicUsers.put("Valentina", "valentina@gmail.com");
            dicUsers.put("Andre", "andre@gmail.com");
            dicUsers.put("Melissa", "melissa@gmail.com");
            dicUsers.put("Paulo", "paulo@gmail.com");
            dicUsers.put("Cecilia", "cecilia@gmail.com");
            dicUsers.put("Francisco", "francisco@gmail.com");
            dicUsers.put("Elisa", "elisa@gmail.com");
            dicUsers.put("Marcos", "marcos@gmail.com");
            dicUsers.put("Isadora", "isadora@gmail.com");
            dicUsers.put("Samuel", "samuel@gmail.com");
            dicUsers.put("Ester", "ester@gmail.com");
            dicUsers.put("Davi", "davi@gmail.com");
            dicUsers.put("Rebeca", "rebeca@gmail.com");
            dicUsers.put("Antonio", "antonio@gmail.com");
            dicUsers.put("Sarah", "sarah@gmail.com");
            dicUsers.put("Miguel", "miguel@gmail.com");
            dicUsers.put("Olivia", "olivia@gmail.com");
            dicUsers.put("Arthur", "arthur@gmail.com");
            dicUsers.put("Aurora", "aurora@gmail.com");
            dicUsers.put("Bernardo", "bernardo@gmail.com");
            dicUsers.put("Luna", "luna@gmail.com");
            dicUsers.put("Heitor", "heitor@gmail.com");
            dicUsers.put("Maya", "maya@gmail.com");
            dicUsers.put("Theo", "theo@gmail.com");
            dicUsers.put("Ayla", "ayla@gmail.com");
            dicUsers.put("Gael", "gael@gmail.com");
            dicUsers.put("Heloisa", "heloisa@gmail.com");
            dicUsers.put("Noah", "noah@gmail.com");
            dicUsers.put("Livia", "livia@gmail.com");
            dicUsers.put("Ravi", "ravi@gmail.com");
            dicUsers.put("Antonella", "antonella@gmail.com");
            dicUsers.put("Joaquim", "joaquim@gmail.com");
            dicUsers.put("Agatha", "agatha@gmail.com");
            dicUsers.put("Benjamin", "benjamin@gmail.com");
            dicUsers.put("Catarina", "catarina@gmail.com");
            dicUsers.put("Isaac", "isaac@gmail.com");
            dicUsers.put("Emanuelly", "emanuelly@gmail.com");
            dicUsers.put("Dante", "dante@gmail.com");
            dicUsers.put("Isis", "isis@gmail.com");
            dicUsers.put("Murilo", "murilo@gmail.com");
            dicUsers.put("Liz", "liz@gmail.com");
            dicUsers.put("Bryan", "bryan@gmail.com");
            dicUsers.put("Maitê", "maite@gmail.com");
            dicUsers.put("Emanuel", "emanuel@gmail.com");
            dicUsers.put("Maria Alice", "mariaalice@gmail.com");
            dicUsers.put("Nicolas", "nicolas@gmail.com");
            dicUsers.put("Maria Clara", "mariaclara@gmail.com");
            dicUsers.put("Lorenzo", "lorenzo@gmail.com");
            dicUsers.put("Maria Cecilia", "mariacecilia@gmail.com");
            dicUsers.put("Pietro", "pietro@gmail.com");
            dicUsers.put("Maria Julia", "mariajulia@gmail.com");
            dicUsers.put("Lucca", "lucca@gmail.com");
            dicUsers.put("Maria Luiza", "marialuiza@gmail.com");
            dicUsers.put("Bento", "bento@gmail.com");
            dicUsers.put("Maria Eduarda", "mariaeduarda@gmail.com");
            dicUsers.put("Levi", "levi@gmail.com");
            dicUsers.put("Ana Julia", "anajulia@gmail.com");
            dicUsers.put("Joao Miguel", "joaomiguel@gmail.com");
            dicUsers.put("Ana Luiza", "analuiza@gmail.com");
            dicUsers.put("Joao Pedro", "joaopedro@gmail.com");
            dicUsers.put("Ana Clara", "anaclara@gmail.com");
            dicUsers.put("Davi Lucca", "davilucca@gmail.com");
            dicUsers.put("Ana Laura", "analaura@gmail.com");
            dicUsers.put("Pedro Henrique", "pedrohenrique@gmail.com");
            dicUsers.put("Mariana", "mariana2@gmail.com");
            dicUsers.put("Joao Lucas", "joaolucas@gmail.com");
            dicUsers.put("Ana Beatriz", "anabeatriz@gmail.com");
            dicUsers.put("Joao Guilherme", "joaoguilherme@gmail.com");
            dicUsers.put("Ana Vitoria", "anavitoria@gmail.com");
            dicUsers.put("Enzo Gabriel", "enzogabriel@gmail.com");
            dicUsers.put("Maria Fernanda", "mariafernanda@gmail.com");
            dicUsers.put("Luiz Felipe", "luizfelipe@gmail.com");
            dicUsers.put("Maria Valentina", "mariavalentina@gmail.com");
            dicUsers.put("Luiz Miguel", "luizmiguel@gmail.com");
            dicUsers.put("Allana", "allana@gmail.com");
            dicUsers.put("Luiz Otavio", "luizotavio@gmail.com");
            dicUsers.put("Alícia", "alicia@gmail.com");
            dicUsers.put("Raul", "raul@gmail.com");
            dicUsers.put("Clarice", "clarice@gmail.com");
            dicUsers.put("Augusto", "augusto@gmail.com");
            dicUsers.put("Eloah", "eloah@gmail.com");
            dicUsers.put("Caua", "caua@gmail.com");
            dicUsers.put("Esther", "esther@gmail.com");
            dicUsers.put("Calebe", "calebe@gmail.com");
            dicUsers.put("Lavinia", "lavinia@gmail.com");
            dicUsers.put("Otavio", "otavio@gmail.com");
            dicUsers.put("Mirella", "mirella@gmail.com");
            dicUsers.put("Vicente", "vicente@gmail.com");
            dicUsers.put("Nicole", "nicole@gmail.com");
            dicUsers.put("Erick", "erick@gmail.com");
            dicUsers.put("Pietra", "pietra@gmail.com");
            dicUsers.put("Ryan", "ryan@gmail.com");
            dicUsers.put("Stella", "stella@gmail.com");
            dicUsers.put("Benicio", "benicio@gmail.com");
            dicUsers.put("Yasmin", "yasmin2@gmail.com");
            dicUsers.put("Danilo", "danilo@gmail.com");
            dicUsers.put("Alexia", "alexia@gmail.com");
            dicUsers.put("Elias", "elias@gmail.com");
            dicUsers.put("Bianca", "bianca@gmail.com");
            dicUsers.put("Luiz Gustavo", "luizgustavo@gmail.com");
            dicUsers.put("Emilly", "emilly@gmail.com");
            dicUsers.put("Kaique", "kaique@gmail.com");
            dicUsers.put("Fernanda", "fernanda@gmail.com");
            dicUsers.put("Nathan", "nathan@gmail.com");
            dicUsers.put("Gabrielly", "gabrielly@gmail.com");
            dicUsers.put("Anthony", "anthony@gmail.com");
            dicUsers.put("Giovanna", "giovanna@gmail.com");
            dicUsers.put("Luiz Henrique", "luizhenrique@gmail.com");
            dicUsers.put("Isabel", "isabel@gmail.com");
            dicUsers.put("Thales", "thales@gmail.com");
            dicUsers.put("Joana", "joana@gmail.com");
            dicUsers.put("Yuri", "yuri@gmail.com");
            dicUsers.put("Lara", "lara@gmail.com");
            dicUsers.put("Breno", "breno@gmail.com");
            dicUsers.put("Livia Maria", "liviamaria@gmail.com");
            dicUsers.put("Enrico", "enrico@gmail.com");
            dicUsers.put("Louise", "louise@gmail.com");
            dicUsers.put("Kevin", "kevin@gmail.com");
            dicUsers.put("Marina", "marina@gmail.com");
            dicUsers.put("Lucas Gabriel", "lucasgabriel@gmail.com");
            dicUsers.put("Milena", "milena@gmail.com");
            dicUsers.put("Vitor", "vitor@gmail.com");
            dicUsers.put("Nina", "nina@gmail.com");
            dicUsers.put("Hugo", "hugo@gmail.com");
            dicUsers.put("Sara", "sara@gmail.com");
            dicUsers.put("Kauê", "kaue@gmail.com");
            dicUsers.put("Sophia", "sophia@gmail.com");
            dicUsers.put("Ian", "ian@gmail.com");
            dicUsers.put("Sophie", "sophie@gmail.com");
            dicUsers.put("Julio Cesar", "juliocesar@gmail.com");
            dicUsers.put("Taina", "taina@gmail.com");
            dicUsers.put("Vitor Hugo", "vitorhugo@gmail.com");
            dicUsers.put("Ana Sophia", "anasophia@gmail.com");
            dicUsers.put("Thiago Henrique", "thiagohenrique@gmail.com");
            dicUsers.put("Agnes", "agnes@gmail.com");
            dicUsers.put("Fabio", "fabio@gmail.com");
            dicUsers.put("Alana", "alana@gmail.com");
            dicUsers.put("Renan", "renan@gmail.com");
            dicUsers.put("Brenda", "brenda@gmail.com");
            dicUsers.put("Jonas", "jonas@gmail.com");
            dicUsers.put("Diana", "diana@gmail.com");
            dicUsers.put("Leandro", "leandro@gmail.com");
            dicUsers.put("Eduarda", "eduarda@gmail.com");
            dicUsers.put("Silas", "silas@gmail.com");
            dicUsers.put("Evelyn", "evelyn@gmail.com");
            dicUsers.put("Abner", "abner@gmail.com");
            dicUsers.put("Fabiana", "fabiana@gmail.com");
            dicUsers.put("Adriano", "adriano@gmail.com");
            dicUsers.put("Fatima", "fatima@gmail.com");

            for (Map.Entry<String, String> entry : dicUsers.entrySet()) {
                String username = entry.getKey();
                String email = entry.getValue();
                client.insert(table, username, email);
            }

            System.out.println("Usuarios da Table " + table);
            client.select(table);

        } catch (RuntimeException e) {
            throw new RuntimeException(e);
        }
    }
}